### PR TITLE
Port to SDL2

### PR DESCRIPTION
**Pull request by dangu**
I really like this game but I was having trouble playing on my computer with multiple monitors. I had to disable all but one of my monitors to play in full screen mode.

This is a branch using SDL2 which offers much better functionality handling multiple monitors. I have started porting the game in Linux and it kind of works now. One major issue is that the menu is not working at all: No text is showing and the mouse movement is not fully synchronized with the button positions in the menu.

Edit 22 Jul 2020: Added a fix for the text: Now the menu text is showing. Also added a fix for the mouse coordinates but it is still not completely synced to the menu buttons.

### CODE REVIEW

**Comment by dangu** [comment]
Menu coordinates seems to be working now.

**Comment by koutoftimer** [comment]
@AMDmi3 this pull request is about SDL2, 1.04 uses SDL.

**Comment by AMDmi3** [comment]
What?

**Comment by DusteDdk** [comment]
wow, that's excellent!

**Pull request merged**
